### <p style="color:#15ef91; font-family:Goudy Stout;  font-size:100%;"><b>Project:- Medical CHATBOT</b> </p>

**This notebook is not complete I'm still working on this project**

#  <b><span style='color:#15ef91 ; font-family:Goudy Stout'>Dataset Description</span></b>

### ***`I have a complete medical chatbot dataset that contains questions, replies, tags, and labels. Here is a breakdown of each column.`***

#### **<h1 align="left"><span style="color:#15ef91;">Classes Of Dataset</span>**

### ***`short_question: This column stores the user's queries or questions.`***
### ***`Short_answer: These are the responses or answers to the user's queries.`***
### ***`tags: This column contains the relevant tags or keywords associated with each question-answer pair, which provide additional context or information`***
### ***`label: This column shows the label or category of each question-answer pair. A label of 1 usually represents a positive response or affirmation, whereas -1 represents a negative response or rejection.`***
#### **<h1 align="left"><span style="color:#15ef91;">About Dataset</span>**

    
### ***`This dataset is used to train a model to understand and respond to various medical queries in order to create a chatbot. I built the chatbot using techniques such as natural language processing (NLP) and machine learning. In addition, I use the tags column to help the model understand the context, and the label column to train it to respond appropriately.`***

#### **<h1 align="center"><span style="color:#15ef91;">Introduction</span>**
### ***👋 Greetings, all! I'm Mohsin Saleem, and I'd want to introduce myself to you. I'm a young data scientist that appreciates using data to acquire valuable insights and make critical decisions. With a strong interest in exploring the domains of data science, I actively participate in many projects and offer my knowledge on platforms such as Kaggle.***

#### **<h1 align="center"><span style="color:#15ef91;">About Me</span>**
### ***🔍 As a young Data Scientist, I'm always seeking for new ways to analyze, understand, and visualize data to solve real-world challenges. My passion for unraveling patterns, discovering trends, and uncovering hidden insights in complex datasets drives my profession in data science.***

### <p style="color:#15ef91; font-family:Goudy Stout;  font-size:100%;"><b>you can Connect with me</b> </p>

[linkedin](www.linkedin.com/in/mohsinsial)\
[github](https://github.com/Mohsin-Sial099)\
[twitter](https://twitter.com/Mohsins90116065)\
[Gmail](mohsinsial250@gmail.com)

#  <b><span style='color:#15ef91 ; font-family:Goudy Stout'> Load Libraries</span></b>

In [1]:
import numpy as np 
import pandas as pd
import os

#  <b><span style='color:#15ef91 ; font-family:Goudy Stout'>Import dataset</span></b>

In [2]:
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/medical-chatbot-dataset/validation_data_chatbot.csv
/kaggle/input/medical-chatbot-dataset/train_data_chatbot.csv

#  <b><span style='color:#15ef91 ; font-family:Goudy Stout'>Checking Head of Validation data</span></b>

In [3]:
test_data = pd.read_csv('/kaggle/input/medical-chatbot-dataset/validation_data_chatbot.csv')

In [4]:
test_data.head()

,short_question,short_answer,tags,label
0,do i have a yeast infection,hi this can be a vaginal fungal infection whic...,['yeast infection'],1.0
1,does your upper backlung area hurt badly with ...,if you have a true allergy to sulfa medication...,['asthma' 'ibuprofen' 'lung' 'cough' 'inhaler'],-1.0
2,taken off paxil cold turk now on celexa having...,if overdose is suspected contact a poison cont...,['brain' 'lightheadedness' 'dizziness' 'coldne...,-1.0
3,i need to buy health insurance asap what do i ...,go to healthcare gov call my husband 407 222 9...,[''],1.0
4,what happens if a pregnant woman has genital h...,sorry for her pain i understand your feelings ...,['genital herpes' 'pregnancy'],-1.0

#  <b><span style='color:#15ef91 ; font-family:Goudy Stout'> Checking Head of Train Dataset</span></b>

In [5]:
train_data = pd.read_csv('/kaggle/input/medical-chatbot-dataset/train_data_chatbot.csv')

In [6]:
train_data.head()

,short_question,short_answer,tags,label
0,can an antibiotic through an iv give you a ras...,yes it can even after you have finished the pr...,['rash' 'antibiotic'],1.0
1,can you test positive from having the hep b va...,test positive for what if you had a hep b vacc...,['hepatitis b'],1.0
2,what are the dietary restrictions for celiac d...,omitting gluten from the diet is the key to co...,['celiac disease'],1.0
3,can i transmit genital warts seventeen years a...,famotidine pepcid products is in a drug class ...,['wart'],-1.0
4,is all vitamin d the same,hi this means you do not have hepatitis b and ...,['vitamin d'],-1.0

#  <b><span style='color:#15ef91 ; font-family:Goudy Stout'>Concatenate Data</span></b>

In [7]:
df = pd.concat([train_data, test_data], ignore_index = True)
df.to_csv("Medical.csv", index = False)

#  <b><span style='color:#15ef91 ; font-family:Goudy Stout'>Head of Concatenate</span></b>

In [8]:
df.head()

,short_question,short_answer,tags,label
0,can an antibiotic through an iv give you a ras...,yes it can even after you have finished the pr...,['rash' 'antibiotic'],1.0
1,can you test positive from having the hep b va...,test positive for what if you had a hep b vacc...,['hepatitis b'],1.0
2,what are the dietary restrictions for celiac d...,omitting gluten from the diet is the key to co...,['celiac disease'],1.0
3,can i transmit genital warts seventeen years a...,famotidine pepcid products is in a drug class ...,['wart'],-1.0
4,is all vitamin d the same,hi this means you do not have hepatitis b and ...,['vitamin d'],-1.0

#  <b><span style='color:#15ef91 ; font-family:Goudy Stout'>Word Tokenization</span></b>

In [9]:
import nltk
from nltk.tokenize import word_tokenize
def tokenize_text(text):
    tokens = word_tokenize(str(text))
    return tokens
for col in df.columns:
    df[col + '_tokens'] = df[col].apply(tokenize_text)
df.to_csv("tokenized_data.csv", index=False)

#  <b><span style='color:#15ef91 ; font-family:Goudy Stout'>Concatenate Dataset</span></b>

In [ ]:
data = pd.read_csv("tokenized_data.csv")

#  <b><span style='color:#15ef91 ; font-family:Goudy Stout'>Tranform into Lowercase</span></b>

In [11]:
def lowercase_text(text):
    return str(text).lower()
df = data.applymap(lowercase_text)

/tmp/ipykernel_33/2802765132.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = data.applymap(lowercase_text)

#  <b><span style='color:#15ef91 ; font-family:Goudy Stout'>Removing Noise </span></b>

In [12]:
import re

def remove_noise(text):
    text = re.sub(r'<.*?>', '', str(text))
    text = re.sub(r'[^\w\s]', '', text)
    return text
dff = df.applymap(remove_noise)

/tmp/ipykernel_33/3278415487.py:7: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  dff = df.applymap(remove_noise)

#  <b><span style='color:#15ef91 ; font-family:Goudy Stout'>Applying Stopwords </span></b>

In [13]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
def remove_stopwords(text):
    words = text.split()  # Split text into words
    filtered_words = [word for word in words if word.lower() not in stop_words]  # Remove stopwords
    return ' '.join(filtered_words)  # Join filtered words back into a string

# Apply stopword removal to all columns
stdf = dff.applymap(remove_stopwords)

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

/tmp/ipykernel_33/2862072571.py:11: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  stdf = dff.applymap(remove_stopwords)

#  <b><span style='color:#15ef91 ; font-family:Goudy Stout'>Applying PorterStemmer </span></b>

In [ ]:
import nltk
from nltk.stem import PorterStemmer
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
stemmer = PorterStemmer()
def stem_text(text):
    words = nltk.word_tokenize(str(text))  # Tokenize text
    stemmed_words = [stemmer.stem(word) for word in words]  # Stem each word
    return ' '.join(stemmed_words)  # Join stemmed words back into a string
stmdf = stdf.applymap(stem_text)

[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /usr/share/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

/tmp/ipykernel_33/1891384043.py:10: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  stmdf = stdf.applymap(stem_text)

#  <b><span style='color:#15ef91 ; font-family:Goudy Stout'>Applying TextBlob </span></b>

In [ ]:
from textblob import TextBlob
def spell_check_text(text):
    blob = TextBlob(str(text))
    corrected_text = blob.correct()
    return str(corrected_text)
sss = stmdf.applymap(spell_check_text)